name: SignSystem
version: 2.0
api-version: 1.17
description: Simple Sign System Plugin
load: STARTUP
author: Green_Panda
website: https://github.com/GreenP4nda/SignSystem
main: at.green_panda.signsystem.SignSystem
database: false

commands:
  signsystem:

